project_id = "lrknetzftkezvqmcincb"


[functions.enqueue-messages]
# No authentication required - public access
verify_jwt = false

[functions.process-message-queue]
# No authentication required - public access
verify_jwt = false